### ISSUE TITLE
A JavaScript Octokit

### ISSUE THREAD

**Issue by zeke** [octokit/discussions#1]
JavaScript is the [world's most popular programming language](https://insights.stackoverflow.com/survey/2017#technology-programming-languages), but it doesn't yet have an [octokit](https://github.com/octokit). We want to change that!

There are lots of JavaScript clients for the GitHub API out there in the wild already. Like, [hundreds](https://github.com/nice-registry/github-api-modules). Instead of creating a new client from scratch, let's look at [what's out there](https://github.com/nice-registry/github-api-modules) and see if there's already a client that could fit the bill.

## Considerations

The following things should be taken into account when evaluating a client:

- Usability - is the client intuitive to use? Can users guess the DSL once they get the hang of it?
- Completeness - does the client support everything that GitHub's REST API offers?
- Flexibility - can the client be adapted to support new GitHub API features like GraphQL?
- Developer Experience - how easy is it for folks to contribute to the project?
- License - permissive enough?

Other considerations that are kind of unique to Javascript:

- Control flow - does the client support Promises? old-school node-style callback? Both?
- Browser support - should the client work in browsers too? How does auth work?
- Node version support - how far back should we support? See [nodejs/LTS](https://github.com/nodejs/LTS)

## Candidates

We've used a number of clients in our projects at GitHub, including [gh-got](http://ghub.io/gh-got), [ghutils](http://ghub.io/ghutils), [octokat](http://ghub.io/octokat), and others. These clients range from minimal to fully-loaded, and each has their own strength.

The client that stands out (to us) as the most "feature-complete" is [github](http://ghub.io/github). It is not only the most popular (by [download count](https://github.com/nice-registry/github-api-modules#top-modules-by-download-count) and [direct dependent count](https://github.com/nice-registry/github-api-modules#top-modules-by-direct-dependent-count)), but it is also generated by a schema, which seems like a promising design approach for being able to sustainably grow and maintain the client over time.

Here's how it stacks up given the above considerations:

- ✅ Usability - intuitive and doesn't try to be too magical, e.g. `github.repos.getCollaborators`
- ✅ Completeness - client is regularly updated as GitHub enables new API features.
- ✅ Flexibility - schema-based design.
- ❓Developer Experience - dev setup is not currently documented
- ✅ Control flow - bring our own `Promise` implementation or use node-style callbacks.
- ✅ License - MIT
- ❓Browser support - not sure
- ✅ Node version support - support back to 0.4.0!

## Feedback, please.

This repo was created to open a dialogue with the open source community about how octokits should be chosen, designed, and maintained. Please feel free to comment here about things I've overlooked, other factors we should be considering, or another JS client that you think would make a great octokit.

**Comment by bkeepers** [comment]
I'm really excited to get an official octokit in JavaScript, so thanks for kicking off this conversation!

FYI @gr2m, and feel free to cc anyone else that you think would have valuable input.

**Comment by bkeepers** [comment]
Also cc @jeffwilcox

**Comment by gr2m** [comment]
We also use [github](https://www.npmjs.com/package/github) in all our projects which interact with the GitHub API, either directly (e.g. greenkeeper.io) or indirectly through [Probot](https://github.com/probot/probot). I promised @bkeepers to give it another thorough look though and see what else is out there today, I’ll report back, can’t give an ETA yet.

In terms of developer experiences, besides documenting the dev setup for `github`, I’d also suggest to modernise the shown examples and use Promises and async/await. We can also do all 3 (callback, promise, async/await) like it’s done on https://pouchdb.com/api.html

In terms of Node.js support, I would strongly recommend to support what ever Node.js is currently supporting, which is Node 4 (maintenance), Node 6 (LTS) and Node 8 (stable) and then move with their LTS schedule. 

PS: @zeke the link behind "github" in "The client that stands out (to us) as the most "feature-complete" is github" is wrong

**Comment by gr2m** [comment]
maybe one thing to consider, which is special for JavaScript, is to break up the library into separate modules, so apps can load only what they need. JavaScript / Node.js is very good at this, and it’s very relevant for front-end application, in order to keep the app size low

**Comment by zombieleet** [comment]
oauth2 ?

**Comment by IonicaBizau** [comment]
> :question: Browser support - not sure

When I wrote [`gh.js`](https://github.com/IonicaBizau/gh.js) what I wanted was same minimal syntax and on the server and in the browser.

Regarding the browser authentication, I added the functionality for optional personal token (to raise the 60 request / hour limit), for personal use (even sharing a scopeless token doesn't seem to be risky).

So, my point of view is that there should be something that can be used in the browser. Since it's JavaScript, most of the code can be isomorphic. :rocket:

**Comment by JasonEtco** [comment]
For control flow, is there a way we can reliably use `async/await`? I realize that browser support is non-existent, and Node support is `7.6.0`+ but we use it for Probot and its 💯.

**Comment by gr2m** [comment]
@JasonEtco if the library supports native Promises, you can use async/await. [github](https://github.com/mikedeboer/node-github) supports promises, I’d need to check the others

**Comment by IonicaBizau** [comment]
@JasonEtco Maybe using transpilers like Babel for older browsers? From a quick check, Safari, Chrome and Firefox do support async/await already:

> #### `Safari`
> ![screen shot 2017-07-04 at 20 04 56](https://user-images.githubusercontent.com/2864371/27838577-3dab2194-60f4-11e7-97fd-e634c76ab56a.png)

> #### `Chrome`
> ![screen shot 2017-07-04 at 20 06 09](https://user-images.githubusercontent.com/2864371/27838576-3d75463c-60f4-11e7-95aa-5cef86b66f83.png)

> #### `Firefox`
> ![screen shot 2017-07-04 at 20 06 04](https://user-images.githubusercontent.com/2864371/27838578-3db1c67a-60f4-11e7-91d3-4a80dbb4a5b3.png)

**Comment by JasonEtco** [comment]
@gr2m yep - I mean internally, and in our docs. If y'all used Promises to mean "Promises & async/await" then thats cool 👍 

@IonicaBizau - Evergreen browsers are better than I thought! But yeah, for use in-browser we'd probably want to transpile or at least ensure that there is that step in a user's build process.

**Comment by gr2m** [comment]
Some more thoughts on a JavaScript Octokit library

### Modularity

A small file size is critical, especially for browser applications and embedded systems. The best way to achieve that is to only load the code that is actually needed by the app.

Say I want to build an app that is pulling data using GitHub’s GraphQL. Instead of loading a fully fledged library which would supports features the GitHub platform has to offer:

```js
const octokit = require('octokit')({token: 'mysecrettoken'})
const result = await octokit.query(`<GRAPH QL QUERY HERE>`)
```

It would be nice to make it possible to only load the code necessary

```js
const query = require('octokit/query')({token: 'mysecrettoken'})
const result = await query(`<GRAPH QL QUERY HERE>`)
```

This would result in a significant smaller size than the app needs to load in order to send the query.

Instead of loading the library via `require('...')` it would be nice to have pre-build JavaScript files which could be loaded directly on websites, like `<script src="octokit.js"></script>` for the fully fledged library, or `<script src="octokit-query.js"></script>` for the custom build only including the query API.

### Environment-agnostic

JavaScript runs on the Server (e.g. Node.js), on embedded systems (e.g. tessel.io) and many, many different browsers. One thing to consider is that based on the environment, different native APIs exist for sending http requests. For example, modern browsers have [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), older browser only have [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), Node.js has [http](https://nodejs.org/api/http.html) and Electron as [net](https://github.com/electron/electron/blob/master/docs/api/net.md).

We could add an option for a callback which turns an object of options like method, url and headers into a request and returns a promise.

```js
const octokit = require('octokit')({
  request: function ({method, headers, url}) {
    return fetch(url, {method, headers})
  },
  token: 'mysecrettoken'
})
const result = await octokit.query(`<GRAPH QL QUERY HERE>`)
```

It would also be simple for us (or the community) to create a dedicated library that sets a default value for `request` based on the availability of fetch or XHR. All we would need to implement is an `octokit.defaults(options)` method

### Distribution

The JavaScrit Octokit would be published to `npm` as a single pacakge. I don’t think we need to split up into separate packages as I don’t expect `octokit` to heavy or native dependencies that would slow down an `npm install` significantly that separate packages could avoid (for comparison, read [PouchDB’s motivation to become a mono repo for multiple packages](https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4))

### Maintainability

As mentioned above, I think we should be good with a good, old single repository for the main `octokit` package. We can automate releases with [semantic-release](https://github.com/semantic-release/semantic-release) and dependency updates with [Greenkeeper](http://greenkeeper.io/).

**Comment by gr2m** [comment]
think with some effort we can make node-github modular as described in https://github.com/octokit/discussions/issues/1#issuecomment-313578629. I would suggest to just fork it and create your own, with a new package name. That gives you the benefit of being able to introduce changes in the API without thinking about breaking changes.

For GraphQL API we would simply add an `octokit.query` method (and separate `octokit/query` function) to which people can directly pass their query using [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by gr2m** [comment]
note that  [github](https://github.com/mikedeboer/node-github) currently has no built for the browser and has no browserify support.

**Comment by zeke** [comment]
@bkeepers, @kytrinyx, @gr2m, and I met today to discuss next steps. We are going to proceed with blessing [node-github](http://ghub.io/github) as the basis for an official JS octokit, and we've outlined a transition plan here: https://github.com/octokit/discussions/issues/7
